# Generated by Django 4.2.4 on 2023-09-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tb_Registros',
            fields=[
                ('id_ocorrencia', models.AutoField(primary_key=True, serialize=False)),
                ('relato', models.CharField(max_length=500)),
                ('latitude', models.CharField(max_length=45)),
                ('longitude', models.CharField(max_length=45)),
                ('observacao', models.TextField()),
            ],
        ),
    ]
