# Generated by Django 4.2.4 on 2023-09-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tb_registros'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_registros',
            name='data_registro',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='tb_registros',
            name='relato',
            field=models.CharField(max_length=45),
        ),
    ]
