# Generated by Django 4.2.4 on 2023-09-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tb_registros_data_registro_alter_tb_registros_relato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tb_registros',
            options={'verbose_name': 'Tabela de Registro', 'verbose_name_plural': 'Tabela de Registros'},
        ),
        migrations.AddField(
            model_name='tb_registros',
            name='Nome_propriedade',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='tb_registros',
            name='hectares',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tb_registros',
            name='prejuizo',
            field=models.FloatField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tb_registros',
            name='rebanho',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tb_registros',
            name='usuario',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
