# Generated by Django 4.2.4 on 2023-09-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tb_registros_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tb_Pragas',
            fields=[
                ('id_praga', models.AutoField(primary_key=True, serialize=False)),
                ('cultura', models.CharField(max_length=45, null=True)),
                ('espécie_valida', models.CharField(max_length=45, null=True)),
                ('nome_comum', models.CharField(max_length=45)),
                ('nome_comum2', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Tabela de Praga',
                'verbose_name_plural': 'Tabela de Pragas',
            },
        ),
    ]
